### ISSUE TITLE
Panic in SDK functions

### ISSUE THREAD

**Issue by fyrchik** [TrueCloudLab/frostfs-sdk-go#2]
Currently we panic in many situations:
1. We forget to set an obligatory parameter. 
2. Some attribute has unexpected value (`(netmap.NodeInfo).Price()` -- we expect to get it with `FromV2` where an error is processed).
3. Something else?

While I think (1) is ok, others are not IMO. Also in (1) we could provide obligatory parameters explicitly:  hard-to-misuse API is the best. Another option is to have `New` with obligatory parameters and `Set` methods on it (private structure with public interface).

@alexvanin @KirillovDenis @carpawell @realloc @acid-ant

**Comment by carpawell** [comment]
I always thought that libraries should not panic in any "normal" cases. I think it is ok to have an exported error that says "i will not even try to make RPC call, u make stupid things" (for unset obligatory parameters, parameters that lead to dero division, etc) and allow a client to decide if he wants to panic. Otherwise, we force using `recover` if a client _never wants his app to crash_, which is not a true way in `go`.

**Comment by carpawell** [comment]
4. Set a parameter whose value is incorrect (see https://github.com/nspcc-dev/neofs-node/pull/2101)

**Comment by fyrchik** [comment]
Here the only reason for `panic` is insufficiently expressive type system. If you use the code wrong, it is ok to panic, so I don't agree it is not a Go way. But I don't mind returning an error.

**Comment by fyrchik** [comment]
We could panic if client init/dial parameter is invalid.
Let's not panic in the RPCs themselves.
